### ISSUE TITLE
Rethink sticky styling

### ISSUE THREAD

**Issue by darshandsoni** [dohliam/yub#10]
When mucking around with the new dark theme, I realised that every theme that sets the body text to white would render stickies unreadable (because of the pale yellow background).
I attempted to correct this by making the sticky style dynamic, depending on which theme is being used.

![unreadable sticky](https://cloud.githubusercontent.com/assets/10469803/14649003/f6eb7474-0619-11e6-8a48-37c140dc5bd3.png)

So my approach was to go into **commands.js** and specifically to line 375 `if (shtct == "sticky")`.
In here, the sticky is called as a div and styled inline. I assumed that if I remove inline styling and refer to an id or class, then put that id or class in default.css it would still render correctly and allows us to inherit sticky styling from the respective theme's css file.

![screen shot 2016-04-19 at 10 33 42 am](https://cloud.githubusercontent.com/assets/10469803/14649055/41e0748e-061a-11e6-8551-8a7f583a2624.png)

My assumption proved incorrect and for some reason, appending a class or id in there breaks the sticky itself.

Any thoughts on this?

**Comment by dohliam** [comment]
Hm, you're right! It looks like this also applies to the `notepad` command. It should be simple to fix, let me take a look and see what we can do.

**Comment by dohliam** [comment]
So I think I've fixed this -- the key was to define a class called "note" and apply it to both the sticky and the notepad divs.

If you look closely at line 375 you'll see where the problem with setting a new id lies: later on in that line, the div is already given an id (`id="b"). You could style this I suppose, but it's a bit of a hack and it's probably better anyway to set a new class that covers both sticky and notepad, since they both are affected by the same issue.

It's also possible that we might want to style both the sticky and the notepad differently (i.e. to give them different background colours)... in that case we could assign different css classes for them. Let me know if you have a preference one way or the other.

**Comment by dohliam** [comment]
Fixed in latest commits
